#encoding: utf-8

#!/usr/bin/ruby

require 'rubygems'
require 'google/api_client'
require 'trollop'
require 'youtube_it'


# Set DEVELOPER_KEY to the "API key" value from the "Access" tab of the
# Google Developers Console <https://cloud.google.com/console>
# Please ensure that you have enabled the YouTube Data API for your project.
DEVELOPER_KEY = "AIzaSyCE0MVxKIJWDbbcfFBDwqD2PW7Igpo8zwY"
YOUTUBE_API_SERVICE_NAME = "youtube"
YOUTUBE_API_VERSION = "v3"
client = Google::APIClient.new(:key => DEVELOPER_KEY,
                               :authorization => nil)
youtube = client.discovered_api(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION)
yt_client = YouTubeIt::Client.new(:dev_key => DEVELOPER_KEY)

comedians =  [
["Orny Adams standup comedy", "white"],
["Ahmed Ahmed standup comedy", "mei"],
["Max Alexander standup comedy", "white"],
["Dan Allen standup comedy", "white"],
["Fred Allen standup comedy", "white"],
["Steve Allen standup comedy", "white"],
["Tim Allen standup comedy", "white"],
["Woody Allen standup comedy", "white"],
["Rabbi Bob Alper standup comedy", "white"],
["Jeff Altman standup comedy", "white"],
["Louie Anderson standup comedy", "white"],
["Eric André standup comedy", "latino"],
["Aziz Ansari standup comedy", "mei"],
["Craig Anton standup comedy", "white"],
["Dave Attell standup comedy", "white"],
["Rick Aviles standup comedy", "latino"],
["Ben Bailey standup comedy", "white"],
["Maria Bamford standup comedy" "white woman"],
["Arj Barker standup comedy", "mei"],
# ["Roseanne Barr standup comedy", "white woman"],
# ["Chuck Barris standup comedy", "white"],
# ["Todd Barry standup comedy", "white"],
# ["Greg Behrendt standup comedy", "white"],
# ["Richard Belzer standup comedy", "white"],
# ["Doug Benson standup comedy", "white"],
# ["Milton Berle standup comedy", "white", "classic"],
# ["Shelley Berman standup comedy", "white", "classic"],
# ["Sandra Bernhard standup comedy", "white woman"],
# ["Michelle Biloon standup comedy", "White woman"],
# ["Mike Birbiglia standup comedy", "white"],
# ["Joey Bishop standup comedy", "white"],
# ["Lewis Black standup comedy", "white"],
# ["Michael Ian Black standup comedy", "white"],
# ["Chris Bliss standup comedy", "white"],
# ["Josh Blue standup comedy", "white"],
# ["Elayne Boosler standup comedy", "white woman"],
# ["Joey Bragg standup comedy", "white"],
# ["Matt Braunger standup comedy", "white"],
# ["Shaun Eli Breidbart standup comedy", "white"],
# ["Kevin Brennan standup comedy", "white"],
# ["David Brenner standup comedy", "white", "classic"],
# ["Jim Breuer standup comedy", "white"],
# ["Bruce Bruce standup comedy", "black"],
# ["Lenny Bruce standup comedy", "white", "classic"],
# ["Bo Burnham standup comedy", "white"],
# ["Bill Burr standup comedy", "white"],
# ["Hannibal Buress standup comedy", "black"],
# ["Brett Butler standup comedy", "white woman"],
# ["Louis CK standup comedy", "white"],
# ["Frank Caliendo standup comedy", "white"],
# ["Godfrey Cambridge standup comedy", "black"],
# ["Mario Cantone standup comedy", "latino"],
# ["John Caparulo standup comedy", "white"],
# ["John Caponera standup comedy", "white"],
# ["Scott Capurro standup comedy", "white"],
# ["Steve Carell standup comedy", "white"],
# ["George Carlin standup comedy", "white"],
# ["Drew Carey standup comedy", "white"],
# ["Adam Carolla standup comedy", "white"],
# ["Jim Carrey standup comedy", "white"],
# ["Rodney Carrington standup comedy", "white"],
# ["Carrot Top  standup comedy", "white"],
# ["Darren Carter standup comedy", "white"],
# ["Jack Carter standup comedy", "white"],
# ["Dana Carvey standup comedy", "white"],
# ["Kyle Cease standup comedy", "white"],
# ["Cedric the Entertainer standup comedy", "black"],
# ["Dave Chappelle standup comedy", "black"],
# ["Henry Cho standup comedy", "asian"],
# ["Margaret Cho standup comedy", "asian woman"],
# ["Blake Clark standup comedy", "white"],
# ["Andrew Dice Clay standup comedy", "white"],
# ["Kate Clinton standup comedy", "white woman"],
# ["Bobby Collins standup comedy", "white"],
# ["Kaitlin Colombo standup comedy", "white woman"],
# ["Ray Combs standup comedy", "white"],
# ["Dane Cook standup comedy", "white"],
# ["Bill Cosby standup comedy", "black"],
# ["Dave Coulier standup comedy", "white"],
# ["David Cross standup comedy", "white"],
# ["Billy Crystal standup comedy", "white"],
# ["Godfrey Danchimah standup comedy", "black"],
# ["Rodney Dangerfield standup comedy", "white", "classic"],
# ["Jim David standup comedy", "white"],
# ["Larry David standup comedy", "white"],
# ["Dov Davidoff standup comedy", "white"],
# ["DeRay Davis standup comedy", "black"],
# ["Frank DeCaro standup comedy", "white"],
# ["Ellen DeGeneres standup comedy", "white woman"],
# ["Nick DiPaolo standup comedy", "white"],
# ["Dustin Diamond standup comedy", "white"],
# ["Andy Dick standup comedy", "white"],
# ["Phyllis Diller standup comedy", "white woman"],
# ["Jeff Dunham standup comedy", "white"],
# ["Jeff Dye standup comedy", "white"],
# ["Sally Edwards standup comedy", "white woman"],
# ["Bill Engvall standup comedy", "white"],
# ["Mike Epps standup comedy", "black"],
# ["Susie Essman standup comedy", "white woman"],
# ["Jade Esteban Estrada standup comedy", "latino"],
# ["Mitch Fatel standup comedy", "white"],
# ["Wayne Federman standup comedy", "white"],
# ["Adam Ferrara standup comedy", "white"],
# ["Christian Finnegan standup comedy", "white"],
# ["Greg Fitzsimmons standup comedy", "white"],
# ["Maile Flanagan standup comedy", "white woman"],
# ["Charles Fleischer standup comedy", "white"],
# ["Jim Florentine standup comedy", "white"],
# ["John Fox standup comedy", "white"],
# ["Kirk Fox standup comedy", "white"],
# ["Jeff Foxworthy standup comedy", "white"],
# ["Jamie Foxx standup comedy", "black"],
# ["Redd Foxx standup comedy", "black"],
# ["Pablo Francisco standup comedy", "latino"],
# ["Jim Gaffigan standup comedy", "white"],
# ["Zach Galifianakis standup comedy", "white"],
# ["Billy Gardell standup comedy", "white"],
# ["Jeff Garlin standup comedy", "white"],
# ["Janeane Garofalo standup comedy", "white woman"],
# ["Brad Garrett standup comedy", "white"],
# ["Greg Giraldo standup comedy", "white"],
# ["Adele Givens standup comedy", "black woman"],
# ["Todd Glass standup comedy", "white"],
# ["Donald Glover standup comedy", "black"],
# ["Judy Gold standup comedy", "white woman"],
# ["Whoopi Goldberg standup comedy", "black woman"],
# ["Bob Golub standup comedy", "white"],
# ["Marga Gomez standup comedy", "latino woman"],
# ["Gilbert Gottfried standup comedy", "white"],
# ["Dana Gould standup comedy", "white"],
# ["Shecky Greene standup comedy", "white", "classic"],
# ["Dick Gregory standup comedy", "black"],
# ["James Gregory standup comedy", "white"],
# ["David Alan Grier standup comedy", "black"],
# ["Eddie Griffin standup comedy", "black"],
# ["Kathy Griffin standup comedy", "white woman"],
# ["Andy Griffith standup comedy", "white"],
# ["Gary Gulman standup comedy", "white"],
# ["Buddy Hackett standup comedy", "white"],
# ["Brian Haley standup comedy", "white"],
# ["Arsenio Hall standup comedy", "black"],
# ["Nathan Hall standup comedy", "white"],
# ["Rich Hall standup comedy", "white"],
# ["Ashley Hamilton standup comedy", "white"],
# ["Darrell Hammond standup comedy", "white"],
# ["Chelsea Handler standup comedy", "white woman"],
# ["Chris Hardwick standup comedy", "white"],
# ["Johnny Hardwick standup comedy", "white"],
# ["Ralph Harris standup comedy", "black"],
# ["Kevin Hart standup comedy", "black"],
# ["Steve Harvey standup comedy", "black"],
# ["Drew Hastings standup comedy", "white"],
# ["Allan Havey standup comedy", "white"],
# ["Mitch Hedberg standup comedy", "white"],
# ["Bill Hicks standup comedy", "white"],
# ["René Hicks standup comedy", "black woman"],
# ["Steve Hofstetter standup comedy", "white"],
# ["Pete Holmes standup comedy", "white"],
# ["Bob Hope standup comedy", "white", "classic"],
# ["DL Hughley standup comedy", "black"],
# ["Reginald D Hunter standup comedy", "black"],
# ["Gabriel Iglesias standup comedy", "latino"],
# ["Dom Irrera standup comedy", "white"],
# ["Clinton Jackson standup comedy", "black"],
# ["Kevin James standup comedy", "white"],
# ["Richard Jeni standup comedy", "white"],
# ["Anthony Jeselnik standup comedy", "mei"],
# ["Maz Jobrani standup comedy", "white"],
# ["Jake Johannsen standup comedy", "white"],
# ["Leslie Jordan standup comedy", "white"],
# ["Aron Kader standup comedy", "white"],
# ["Cory Kahaney standup comedy", "white woman"],
# ["Moshe Kasher standup comedy", "white"],
# ["Andy Kaufman standup comedy", "white"],
# ["Jamie Kennedy standup comedy", "white"],
# ["Kyle Kinane standup comedy", "white"],
# ["Andy Kindler standup comedy", "white"],
# ["Alan King standup comedy", "white"],
# ["Sam Kinison standup comedy", "white"],
# ["Jen Kirkman standup comedy", "white woman"],
# ["Robert Klein standup comedy", "white"],
# ["Jeff Klinger standup comedy", "white"],
# ["Don Knotts standup comedy", "white"],
# ["Rebekah Kochan standup comedy", "white woman"],
# ["Lynne Koplitz standup comedy", "white"],
# ["Jo Koy standup comedy", "asian"],
# ["Lisa Lampanelli standup comedy", "white woman"],
# ["Lisa Landry standup comedy", "white woman"],
# ["Artie Lange standup comedy", "white"],
# ["Larry the Cable Guy standup comedy", "white"],
# ["Martin Lawrence standup comedy", "black"],
# ["Denis Leary standup comedy", "white"],
# ["Natasha Leggero standup comedy", "white woman"],
# ["John Leguizamo standup comedy", "latino"],
# ["Tom Lehrer standup comedy", "white"],
# ["Carol Leifer standup comedy", "white woman"],
# ["Wendy Liebman standup comedy", "white woman"],
# ["Rob Little standup comedy", "white"],
# ["Jay London standup comedy", "white"],
# ["George Lopez standup comedy", "latino"],
# ["Jason Love standup comedy", "white"],
# ["Loni Love standup comedy", "black woman"],
# ["Jon Lovitz standup comedy", "white"],
# ["Stephen Lynch standup comedy", "white"],
# ["Bernie Mac standup comedy", "black"],
# ["Norm Macdonald standup comedy", "white"],
# ["Kathleen Madigan standup comedy", "white"],
# ["Al Madrigal standup comedy", "latino"],
# ["Bill Maher standup comedy", "white"],
# ["Keith Malley standup comedy", "white"],
# ["Cheech Marin standup comedy", "latino"],
# ["Bob Marley standup comedy", "white"],
# ["Marc Maron standup comedy", "white"],
# ["Steve Martin standup comedy", "white"],
# ["Demetri Martin standup comedy", "white"],
# ["Marilyn Martinez standup comedy", "latino woman"],
# ["Jackie Martling standup comedy", "white"],
# ["Jackie Mason standup comedy", "white", "classic"],
# ["Ralphie May standup comedy", "white"],
# ["Jonny McGovern standup comedy", "white"],
# ["Joel McHale standup comedy", "white"],
# ["Kevin Meaney standup comedy", "white"],
# ["Anne Meara standup comedy", "white woman"],
# ["Carlos Mencia standup comedy", "latino"],
# ["Russ Meneve standup comedy", "white"],
# ["Seth Meyers standup comedy", "white"],
# ["Dennis Miller standup comedy", "white"],
# ["George Miller standup comedy", "white"],
# ["Larry Miller standup comedy", "white"],
# ["Eugene Mirman standup comedy", "white"],
# ["MoNique standup comedy", "black woman"],
# ["Tracy Morgan standup comedy", "black"],
# ["Paul Mooney standup comedy", "black"],
# ["Rudy Ray Moore standup comedy", "black"],
# ["Kevin Moyers standup comedy", "white"],
# ["John Mulaney standup comedy", "white"],
# ["Charlie Murphy standup comedy", "black"],
# ["Eddie Murphy standup comedy", "black"],
# ["Noel Murphy standup comedy", "white"],
# ["Kumail Nanjiani standup comedy", "mei"],
# ["Bob Newhart standup comedy", "white"],
# ["Adam Newman standup comedy", "white"],
# ["Lance Norris standup comedy", "white"],
# ["Jim Norton standup comedy", "white"],
# ["Tig Notaro standup comedy", "white woman"],
# ["Dean Obeidallah standup comedy", "white"],
# ["Paul Ogata standup comedy", "asian"],
# ["Patrice O Neal standup comedy", "black"],
# ["Patton Oswalt standup comedy", "white"],
# ["Jimmy Pardo standup comedy", "white"],
# ["John Pinette standup comedy", "white"],
# ["Aubrey Plaza standup comedy", "white woman"],
# ["Brian Posehn standup comedy", "white"],
# ["Paula Poundstone standup comedy", "white woman"],
# ["Marc Price standup comedy", "white"],
# ["Freddie Prinze standup comedy", "white"],
# ["Greg Proops standup comedy", "white"],
# ["Paul Provenza standup comedy", "white"],
# ["Richard Pryor standup comedy", "black"],
# ["Colin Quinn standup comedy", "white"],
# ["David Race standup comedy", "white"],
# ["Brian Regan standup comedy", "white"],
# ["Paul Reiser standup comedy", "white"],
# ["Michael Richards standup comedy", "white"],
# ["Don Rickles standup comedy", "white"],
# ["Joan Rivers standup comedy", "white woman"],
# ["Craig Robinson standup comedy", "black"],
# ["Chris Rock standup comedy", "black"],
# ["Paul Rodriguez standup comedy", "latino"],
# ["Joe Rogan standup comedy", "white"],
# ["Seth Rogen standup comedy", "white"],
# ["Ray Romano standup comedy", "white"],
# ["Jeffrey Ross standup comedy", "white"],
# ["Rita Rudner standup comedy", "white"],
# ["Bob Saget standup comedy", "white"],
# ["Tim Sample standup comedy", "white"],
# ["Adam Sandler standup comedy", "white"],
# ["Lewis Schaffer standup comedy", "white"],
# ["Mark Schiff standup comedy", "white"],
# ["Robert Schimmel standup comedy", "white"],
# ["Amy Schumer standup comedy", "white woman"],
# ["Jerry Seinfeld standup comedy", "white"],
# ["Garry Shandling standup comedy", "white"],
# ["Rick Shapiro standup comedy", "white"],
# ["Ron Shock standup comedy", "white"],
# ["Craig Shoemaker standup comedy", "white"],
# ["Ritch Shydner standup comedy", "white"],
# ["Sarah Silverman standup comedy", "white woman"],
# ["Brad Slaight standup comedy", "white"],
# ["Bobby Slayton standup comedy", "white"],
# ["Yakov Smirnoff standup comedy", "white"],
# ["Margaret Smith standup comedy", "white woman"],
# ["Sommore standup comedy", "black woman"],
# ["David Spade standup comedy", "white"],
# ["Doug Stanhope standup comedy", "white"],
# ["Brody Stevens standup comedy", "white"],
# ["Jon Stewart standup comedy", "white"],
# ["Jerry Stiller standup comedy", "white"],
# ["Brad Stine standup comedy", "white"],
# ["Fred Stoller standup comedy", "white"],
# ["Ryan Stout standup comedy", "white"],
# ["Nick Swardson standup comedy", "white"],
# ["Wanda Sykes standup comedy", "black woman"],
# ["Tim Tayag standup comedy", "asian"],
# ["Judy Tenuta standup comedy", "white womab"],
# ["Danny Thomas standup comedy", "white", "classic"],
# ["Jimmy Tingle standup comedy", "white"],
# ["Christopher Titus standup comedy", "white"],
# ["Lily Tomlin standup comedy", "white woman"],
# ["Paul F. Tompkins standup comedy", "white"],
# ["Daniel Tosh standup comedy", "white"],
# ["Rosie Tran standup comedy", "asian woman"],
# ["Fred Travalena standup comedy", "white"],
# ["Greg Travis standup comedy", "white"],
# ["Chris Tucker standup comedy", "black"],
# ["Rich Vos standup comedy", "white"],
# ["Jimmie Walker standup comedy", "black"],
# ["Greg Warren standup comedy", "white"],
# ["Damon Wayans standup comedy", "black"],
# ["Keenen Ivory Wayans standup comedy", "black"],
# ["Shawn Wayans standup comedy", "black"],
# ["Suzanne Westenhoefer standup comedy", "white woman"],
# ["Ron White standup comedy", "white"],
# ["Katt Williams standup comedy", "black"],
# ["Robin Williams standup comedy", "white"],
# ["Flip Wilson standup comedy", "black"],
# ["Michael Winslow standup comedy", "black"],
# ["Jonathan Winters standup comedy", "last_check"],
# ["Mark Wirtz standup comedy", "white"],
# ["Harris Wittels standup comedy", "white"],
# ["Dennis Wolfberg standup comedy", "white"],
# ["Steven Wright standup comedy", "white"],
# ["Dylan Moran standup comedy", "white"],
# ["Ralphie May standup comedy", "white"],
# ["Aaron Edwards standup comedy", "white"],
# ["Aaron Foster standup comedy", "white"],
# ["Aaron Sutherland standup comedy", "white"],
# ["Aaron Weaver standup comedy", "white"],
# ["Aarona Lopez standup comedy", "white"],
# ["Abi Sanchez standup comedy", "latino"],
# ["AC Cunningham standup comedy", "white"],
# ["Ace Guillen standup comedy", "white"],
# ["Adam Burke standup comedy", "white"],
# ["Adam Carolla standup comedy", "white"],
# ["Adam DeVine standup comedy", "white"],
# ["Adam Epelbaum standup comedy", "white"],
# ["Adam Ferrara standup comedy", "white"],
# ["Adam Grabowski standup comedy", "white"],
# ["Adam Hammer standup comedy", "white"],
# ["Adam Hunter standup comedy", "white"],
# ["Adam Lowitt standup comedy", "white"],
# ["Adam Lustick standup comedy", "white"],
# ["Adam Ray standup comedy", "white"],
# ["Aditi Mittal standup comedy", "white"],
# ["Ahmed Ahmed standup comedy", "white"],
# ["Aida Rodriguez standup comedy", "white"],
# ["Aidan Park standup comedy", "white"],
# ["AJ Lubecker standup comedy", "white"],
# ["Al Del Bene standup comedy", "white"],
# ["Al Ducharme standup comedy", "white"],
# ["Al Lubel standup comedy", "white"],
# ["Al Madrigal standup comedy", "latino"],
# ["Alan Bursky standup comedy", "white"],
# ["Alan Committie standup comedy", "white"],
# ["Alan Grafton standup comedy", "white"],
# ["Alex Orozco standup comedy", "white"],
# ["Alex Ortiz standup comedy", "white"],
# ["Alex Scott standup comedy", "white"],
# ["Alex Stein standup comedy", "white"],
# ["Alex Stone standup comedy", "white"],
# ["Alex Thomas standup comedy", "white"],
# ["Alex Vergel standup comedy", "white"],
# ["Alfred Robles standup comedy", "white"],
# ["Ali Clayton standup comedy", "white"],
# ["Ali Hassan standup comedy", "white"],
# ["Alice Wetterlund standup comedy", "white"],
# ["Allan Murray standup comedy", "white"],
# ["Allan Stephan standup comedy", "white"],
# ["Alli Breen standup comedy", "white"],
# ["Alonzo Bodden standup comedy", "black"],
# ["Alycia Cooper standup comedy", "white"],
# ["Amir K standup comedy", "mei"],
# ["Amy Schumer standup comedy", "white"],
# ["Amy Sumpter standup comedy", "white"],
# ["Amy Swartz standup comedy", "white"],
# ["Amy Tee standup comedy", "white"],
# ["Andi Osho standup comedy", "white"],
# ["Andi Smith standup comedy", "white"],
# ["Andie Bolt standup comedy", "white"],
# ["Andre Kelley standup comedy", "white"],
# ["Andrew Berkovich standup comedy", "white"],
# ["Andrew Norelli standup comedy", "white"],
# ["Andrew Santino standup comedy", "white"],
# ["Andrey Belikov standup comedy", "white"],
# ["Andy Fleming standup comedy", "white"],
# ["Andy Haynes standup comedy", "white"],
# ["Andy Kindler standup comedy", "white"],
# ["Andy Kozel standup comedy", "white"],
# ["Andy Peters standup comedy", "white"],
# ["Angelo Tsarouchas standup comedy", "white"],
# ["Angus Hamilton standup comedy", "white"],
# ["Anjelah Johnson standup comedy", "white"],
# ["Annie Lederman standup comedy", "white"],
# ["Anthony Bonazzo standup comedy", "white"],
# ["Anthony Griffith standup comedy", "white"],
# ["Anthony Jeselnik standup comedy", "white"],
# ["April Macie standup comedy", "white"],
# ["Archer Coe standup comedy", "white"],
# ["Argus Hamilton standup comedy", "white"],
# ["Ari Shaffir standup comedy", "white"],
# ["Aries Spears standup comedy", "white"],
# ["Aristotle Athiras standup comedy", "white"],
# ["Armando Cosio Sr. standup comedy", "white"],
# ["Armando Pops Cosio Jr. standup comedy", "white"],
# ["Aron Kader standup comedy", "white"],
# ["Ashley Hamilton standup comedy", "white"],
# ["Asif Ali standup comedy", "white"],
# ["Assad Motavasseli standup comedy", "white"],
# ["Aurelio Bocanegra standup comedy", "white"],
# ["Avi LibermanAvi standup comedy", "white"],
# ["B.Cole standup comedy", "white"],
# ["Barbara Gray standup comedy", "white"],
# ["Baron Vaughn standup comedy", "white"],
# ["Barrington Ross standup comedy", "white"],
# ["Barry Diamond standup comedy", "white"],
# ["Barry Rothbart standup comedy", "white"],
# ["Ben Begley standup comedy", "white"],
# ["Ben Bergman standup comedy", "white"],
# ["Ben Gleib standup comedy", "white"],
# ["Ben Morrison standup comedy", "white"],
# ["Benji Aflalo standup comedy", "white"],
# ["Beny Mena standup comedy", "white"],
# ["Beth Stelling standup comedy", "white"],
# ["Betsy Salkind standup comedy", "white"],
# ["Bill Bunker standup comedy", "white"],
# ["Bill Burr standup comedy", "white"],
# ["Bill Cruz standup comedy", "white"],
# ["Bill Dawes standup comedy", "white"],
# ["Bill Kalmenson standup comedy", "white"],
# ["Bill Santiago standup comedy", "white"],
# ["Billy Bonnell standup comedy", "white"],
# ["Billy Rebeck standup comedy", "white"],
# ["Billy Sorrells standup comedy", "white"],
# ["BJ Novak standup comedy", "white"],
# ["Bo Clark standup comedy", "white"],
# ["Bob Dubac standup comedy", "white"],
# ["Bob Golub standup comedy", "white"],
# ["Bob Marley standup comedy", "white"],
# ["Bob Oschack standup comedy", "white"],
# ["Bob Zany standup comedy", "white"],
# ["Bobby Lee standup comedy", "white"],
# ["Bobcat Goldthwait standup comedy", "white"],
# ["Boogie Montrell standup comedy", "white"],
# ["Brad Garrett standup comedy", "white"],
# ["Brad Loekle standup comedy", "white"],
# ["Brad Reeder standup comedy", "white"],
# ["Brad Williams standup comedy", "white"],
# ["Brady Matthews standup comedy", "white"],
# ["Brandon Broady standup comedy", "white"],
# ["Brandon Glover standup comedy", "white"],
# ["Brandon Vestal standup comedy", "white"],
# ["Brandt Tobler standup comedy", "white"],
# ["Brendon Burns standup comedy", "white"],
# ["Brendon Walsh standup comedy", "white"],
# ["Brent Morin standup comedy", "white"],
# ["Bret Ernst standup comedy", "white"],
# ["Brett Riley standup comedy", "white"],
# ["Brian 'Da Wildcat' Smith standup comedy", "white"],
# ["Brian Holtzman standup comedy", "white"],
# ["Brian McKim standup comedy", "white"],
# ["Brian Moote standup comedy", "white"],
# ["Brian O'Sullivan standup comedy", "white"],
# ["Brian Scolaro standup comedy", "white"],
# ["Brian Sheil standup comedy", "white"],
# ["Brian Smith standup comedy", "white"],
# ["Brian Watts standup comedy", "white"],
# ["Brody Stevens standup comedy", "white"],
# ["Brooks Wheelan standup comedy", "white"],
# ["Bruce Jingles standup comedy", "white"],
# ["Bruno Lucia standup comedy", "white"],
# ["Bryan Callen standup comedy", "white"],
# ["Bryan Cook standup comedy", "white"],
# ["Buddy Lewis standup comedy", "white"],
# ["Butch Bradley standup comedy", "white"],
# ["Byron Bowers standup comedy", "white"],
# ["Dr. Brian King standup comedy", "white"],
# ["Caitlin Bergh standup comedy", "white"],
# ["Calvin Evans standup comedy", "white"],
# ["Cameron Esposito standup comedy", "white"],
# ["Camilla Cleese standup comedy", "white"],
# ["Candy Lawrence standup comedy", "white"],
# ["Carl Kozlowski standup comedy", "white"],
# ["Carla Collins standup comedy", "white"],
# ["Carlos Alazraqui standup comedy", "white"],
# ["Carlos Loma standup comedy", "white"],
# ["Carlos Santos standup comedy", "white"],
# ["Casey Balsham standup comedy", "white"],
# ["Cash Levy standup comedy", "white"],
# ["Cathy Ladman standup comedy", "white"],
# ["Charles Sanchez standup comedy", "white"],
# ["Charlie O'Connor standup comedy", "white"],
# ["Chelsea Handler standup comedy", "white"],
# ["Chelsea Peretti standup comedy", "white"],
# ["Chinedu Unaka standup comedy", "white"],
# ["Chip Pope standup comedy", "white"],
# ["Chris 'Scandal' Randall standup comedy", "white"],
# ["Chris Bader standup comedy", "white"],
# ["Chris Compton standup comedy", "white"],
# ["Chris Heward standup comedy", "white"],
# ["Chris James standup comedy", "white"],
# ["Chris Jones standup comedy", "white"],
# ["Chris Kattan standup comedy", "white"],
# ["Chris Marquette standup comedy", "white"],
# ["Chris Millhouse standup comedy", "white"],
# ["Chris Paladino standup comedy", "white"],
# ["Chris Porter standup comedy", "white"],
# ["Chris Redd standup comedy", "white"],
# ["Chris Reid standup comedy", "white"],
# ["Chris Spencer standup comedy", "white"],
# ["Chris Strait standup comedy", "white"],
# ["Chris Velez standup comedy", "white"],
# ["Christian Finnegan standup comedy", "white"],
# ["Christian Shirm standup comedy", "white"],
# ["Christian Spicer standup comedy", "white"],
# ["Christina Davis standup comedy", "white"],
# ["Christina Pazsitzky standup comedy", "white"],
# ["Christopher Bryuant Smith standup comedy", "white"],
# ["Christopher Titus standup comedy", "white"],
# ["Chuy Bravo standup comedy", "white"],
# ["CJ Sullivan standup comedy", "white"],
# ["Clark Jones standup comedy", "white"],
# ["Claude Stuart standup comedy", "white"],
# ["Clayton Thomas standup comedy", "white"],
# ["Cody Melcher standup comedy", "white"],
# ["Cole Parker standup comedy", "white"],
# ["Colin Kane standup comedy", "white"],
# ["Collin Bullock standup comedy", "white"],
# ["Cort McCown standup comedy", "white"],
# ["Cosby Sweaters standup comedy", "white"],
# ["Courney Schuereman standup comedy", "white"],
# ["Craig Shoemaker standup comedy", "white"],
# ["Cynthia Levin standup comedy", "white"],
# ["Damon Williams standup comedy", "white"],
# ["Dan Ahdoot standup comedy", "white"],
# ["Dan Cummins standup comedy", "white"],
# ["Dan Frederickson standup comedy", "white"],
# ["Dan Friesen standup comedy", "white"],
# ["Dan Gabriel standup comedy", "white"],
# ["Dan Levy standup comedy", "white"],
# ["Dan Ronan standup comedy", "white"],
# ["Dan Rosenberg standup comedy", "white"],
# ["Dan Soder standup comedy", "white"],
# ["Dan St. Germain standup comedy", "white"],
# ["Dana Carvey standup comedy", "white"],
# ["Dana Eagle standup comedy", "white"],
# ["Dana Goldberg standup comedy", "white"],
# ["Dana Gould standup comedy", "white"],
# ["Daniel Eachus standup comedy", "white"],
# ["Danielle Stewart standup comedy", "white"],
# ["Danno Carter standup comedy", "white"],
# ["Danny Bhoy standup comedy", "white"],
# ["Danny Cho standup comedy", "white"],
# ["Danny Kallas standup comedy", "white"],
# ["Danny Lobell standup comedy", "white"],
# ["Darrell La Montre standup comedy", "white"],
# ["Darren Carter standup comedy", "white"],
# ["Darryl Littleton standup comedy", "white"],
# ["Darwin Hines standup comedy", "white"],
# ["Dave Burleigh standup comedy", "white"],
# ["Dave Foley standup comedy", "white"],
# ["Dave Hanson standup comedy", "white"],
# ["Dave Merheje standup comedy", "white"],
# ["Dave Metcalfe standup comedy", "white"],
# ["Dave Ross standup comedy", "white"],
# ["Dave Siegel standup comedy", "white"],
# ["Dave Stone standup comedy", "white"],
# ["Davey Boy Helem standup comedy", "white"],
# ["David Arnold standup comedy", "white"],
# ["David Drake standup comedy", "white"],
# ["David Feldman standup comedy", "white"],
# ["David Golshan standup comedy", "white"],
# ["David Huntsberger standup comedy", "white"],
# ["David Koechner standup comedy", "white"],
# ["David Newton standup comedy", "white"],
# ["David Philips standup comedy", "white"],
# ["David Spade standup comedy", "white"],
# ["Dax Jordan standup comedy", "white"],
# ["DC Ervin standup comedy", "white"],
# ["Dean Delray standup comedy", "white"],
# ["Dean Edwards standup comedy", "white"],
# ["Debbie Praver standup comedy", "white"],
# ["Debi Gutierrez standup comedy", "white"],
# ["Deepak Sethi standup comedy", "white"],
# ["Denise Ramsden standup comedy", "white"],
# ["Dennis Blair standup comedy", "white"],
# ["Denny Johnston standup comedy", "white"],
# ["Deon Cole standup comedy", "white"],
# ["Devin Field standup comedy", "white"],
# ["Devin Q standup comedy", "white"],
# ["DewaynePerkins standup comedy", "white"],
# ["Diane Neal standup comedy", "white"],
# ["Dick Black standup comedy", "white"],
# ["Dick Gregory standup comedy", "white"],
# ["Dillon Garcia standup comedy", "white"],
# ["Dinah Leffert standup comedy", "white"],
# ["Dom Irrera standup comedy", "white"],
# ["Don Hefty standup comedy", "white"],
# ["Don McEnery standup comedy", "white"],
# ["Donald Glover standup comedy", "white"],
# ["Donell James Foreman standup comedy", "white"],
# ["Donnell Rawlings standup comedy", "white"],
# ["Dov Davidoff standup comedy", "white"],
# ["Drew Anderson standup comedy", "white"],
# ["Drew Frees standup comedy", "white"],
# ["Drew Michael standup comedy", "white"],
# ["Duncan Trussell standup comedy", "white"],
# ["Dustin Ybarra standup comedy", "white"],
# ["Dwayne Kennedy standup comedy", "white"],
# ["Dwayne Perkins standup comedy", "white"],
# ["Marc 'DJ Moose' Moder standup comedy", "white"],
# ["Ed Greer standup comedy", "white"],
# ["Eddie Ifft standup comedy", "white"],
# ["Edwin San Juan standup comedy", "white"],
# ["Elaine Osgood standup comedy", "white"],
# ["Eleanor Kerrigan standup comedy", "white"],
# ["Eli Nicolas standup comedy", "white"],
# ["Eli Olsberg standup comedy", "white"],
# ["Eliot Chang standup comedy", "white"],
# ["Eliza Skinner standup comedy", "white"],
# ["Elon Gold standup comedy", "white"],
# ["Eric Andre standup comedy", "white"],
# ["Eric Giancola standup comedy", "white"],
# ["Eric Hahn standup comedy", "white"],
# ["Eric Jackson standup comedy", "white"],
# ["Eric Lampaert standup comedy", "white"],
# ["Eric Saleh standup comedy", "white"],
# ["Eric Schwartz standup comedy", "white"],
# ["Elon Gold standup comedy", "white"],
# ["Erik Griffin standup comedy", "white"],
# ["Erik Monical standup comedy", "white"],
# ["Erik Myers standup comedy", "white"],
# ["Erik Passoja standup comedy", "white"],
# ["Erin Foley standup comedy", "white"],
# ["Erin Schauer standup comedy", "white"],
# ["Esau McGraw standup comedy", "white"],
# ["Ester Steinberg standup comedy", "white"],
# ["Esther Povitsky standup comedy", "white"],
# ["Evan O'Brien standup comedy", "white"],
# ["Evan Sayet standup comedy", "white"],
# ["Ever Mainard standup comedy", "white"],
# ["Fahim Anwar standup comedy", "white"],
# ["Farty Marty standup comedy", "white"],
# ["Felicia Michaels standup comedy", "white"],
# ["Felipe Esparza standup comedy", "white"],
# ["Feraz Ozel standup comedy", "white"],
# ["Fernando Verdugo standup comedy", "white"],
# ["Fielding Edlow standup comedy", "white"],
# ["Finesse Mitchell standup comedy", "white"],
# ["Finis Henderson standup comedy", "white"],
# ["Flip Schultz standup comedy", "white"],
# ["Fortune Feimster standup comedy", "white"],
# ["Frances Dilorinzo standup comedy", "white"],
# ["Franchie San Pedro standup comedy", "white"],
# ["Francisco Ramos standup comedy", "white"],
# ["Frank Lucero standup comedy", "white"],
# ["Frank NicoteroFrank's Videos standup comedy", "white"],
# ["Frank Townsend standup comedy", "white"],
# ["Frazer Smith standup comedy", "white"],
# ["Freddy Lockhart standup comedy", "white"],
# ["G Reilly standup comedy", "white"],
# ["Garfunkel and Oates standup comedy", "white"],
# ["Garrett Clark standup comedy", "white"],
# ["Gayan Seneviratna standup comedy", "white"],
# ["Gene Pompa standup comedy", "white"],
# ["Geoff Keith standup comedy", "white"],
# ["George Perez standup comedy", "white"],
# ["George Wallace standup comedy", "white"],
# ["Gerard Guillory standup comedy", "white"],
# ["Gerry Bednob standup comedy", "white"],
# ["Gina Yashere standup comedy", "white"],
# ["Glen Martino standup comedy", "white"],
# ["Gloria Bigelow standup comedy", "white"],
# ["Grant Cotter standup comedy", "white"],
# ["Grant Lyon standup comedy", "white"],
# ["Greg Behrendt standup comedy", "white"],
# ["Greg Davies standup comedy", "white"],
# ["Greg Fitzsimmons standup comedy", "white"],
# ["Greg Morton standup comedy", "white"],
# ["Guy Branum standup comedy", "white"],
# ["Gwen La Roka standup comedy", "white"],
# ["Hailey Boyle standup comedy", "white"],
# ["Halli Borgfjord standup comedy", "white"],
# ["Hampton Yount standup comedy", "white"],
# ["Hannah 'Harto' Hart standup comedy", "white"],
# ["Hannibal Buress standup comedy", "white"],
# ["Harland Williams standup comedy", "white"],
# ["Harmony McElligott standup comedy", "white"],
# ["Harris Peet standup comedy", "white"],
# ["Harry Basil standup comedy", "white"],
# ["Hasan Minhaj standup comedy", "white"],
# ["Hasim Outlaw standup comedy", "white"],
# ["Helen Hong standup comedy", "white"],
# ["Henrietta Komras standup comedy", "white"],
# ["Hillary Sawchuk standup comedy", "white"],
# ["Hollie Meyer standup comedy", "white"],
# ["Honest John standup comedy", "white"],
# ["Hope Flood standup comedy", "white"],
# ["Hunter Cope standup comedy", "white"],
# ["Ian Abramson standup comedy", "white"],
# ["Ian Bagg standup comedy", "white"],
# ["ian Edwards standup comedy", "white"],
# ["Ian Harris standup comedy", "white"],
# ["Iliza Shlesinger standup comedy", "white"],
# ["J Chris Newberg standup comedy", "white"],
# ["Jack Michelman standup comedy", "white"],
# ["Jack Robichaud standup comedy", "white"],
# ["Jack Vale standup comedy", "white"],
# ["Jackie Fabulous standup comedy", "white"],
# ["Jackie Johnson standup comedy", "white"],
# ["Jackie Jones standup comedy", "white"],
# ["Jackson McQueen standup comedy", "white"],
# ["Jackson Perdue standup comedy", "white"],
# ["Jacob Sirof standup comedy", "white"],
# ["Jacob Williams standup comedy", "white"],
# ["Jade Catta-Preta standup comedy", "white"],
# ["Jahan Djowharzadeh standup comedy", "white"],
# ["Jaime de Leon standup comedy", "white"],
# ["Jake Dill standup comedy", "white"],
# ["Jake McKenzie standup comedy", "white"],
# ["Jake Weisman standup comedy", "white"],
# ["Jamar Neighbors standup comedy", "white"],
# ["James Adomian standup comedy", "white"],
# ["James Davis standup comedy", "white"],
# ["James Frey standup comedy", "white"],
# ["James Harris standup comedy", "white"],
# ["James Ponce standup comedy", "white"],
# ["James Smith standup comedy", "white"],
# ["Jamie Campbell standup comedy", "white"],
# ["Jamie Kaler standup comedy", "white"],
# ["Jamie Kennedy standup comedy", "white"],
# ["Jamie Lissow standup comedy", "white"],
# ["Jamie Masada standup comedy", "white"],
# ["Jamie Salitas standup comedy", "white"],
# ["Jared Logan standup comedy", "white"],
# ["Jarrod Harris standup comedy", "white"],
# ["Jason Canning standup comedy", "white"],
# ["Jason Collings standup comedy", "white"],
# ["Jason Dudey standup comedy", "white"],
# ["Jason Mewes standup comedy", "white"],
# ["Jason Rouse standup comedy", "white"],
# ["Jason Stuart standup comedy", "white"],
# ["Jawn Koems standup comedy", "white"],
# ["Jay Black standup comedy", "white"],
# ["Jay Chandrasekhar standup comedy", "white"],
# ["Jay Davis standup comedy", "white"],
# ["Jay Larson standup comedy", "white"],
# ["Jay Leno standup comedy", "white"],
# ["Jay London standup comedy", "white"],
# ["Jay Montepare standup comedy", "white"],
# ["Jay Nog standup comedy", "white"],
# ["Jay Oakerson standup comedy", "white"],
# ["Jay Phillips standup comedy", "white"],
# ["Jay Reid standup comedy", "white"],
# ["Jay Washington standup comedy", "white"],
# ["JC Coccoli standup comedy", "white"],
# ["JD Witherspoon standup comedy", "white"],
# ["Jeanie Doogan standup comedy", "white"],
# ["Jeff Altman standup comedy", "white"],
# ["Jeff Arcuri standup comedy", "white"],
# ["Jeff Cesario standup comedy", "white"],
# ["Jeff Conway standup comedy", "white"],
# ["Jeff Garcia standup comedy", "white"],
# ["Jeff Garlin standup comedy", "white"],
# ["Jeff Richards standup comedy", "white"],
# ["Jeff Steinbrunner standup comedy", "white"],
# ["Jeff Urrea standup comedy", "white"],
# ["Jeffrey Ross standup comedy", "white"],
# ["Jen D'Angelo standup comedy", "white"],
# ["Jen Kirkman standup comedy", "white"],
# ["Jen Murphy standup comedy", "white"],
# ["Jennie McNulty standup comedy", "white"],
# ["Jenny Johnson standup comedy", "white"],
# ["Jeremiah Watkins standup comedy", "white"],
# ["Jeremy Hotz standup comedy", "white"],
# ["Jerome Cleary standup comedy", "white"],
# ["Jerrod Carmichael standup comedy", "white"],
# ["Jerry Garcia standup comedy", "white"],
# ["Jerry Rocha standup comedy", "white"],
# ["Jesse Case standup comedy", "white"],
# ["Jessica Glassberg standup comedy", "white"],
# ["Jessica Halem standup comedy", "white"],
# ["Jessica Hudson standup comedy", "white"],
# ["Jessica Kirson standup comedy", "white"],
# ["Jessica Lowe standup comedy", "white"],
# ["Jesus Trejo standup comedy", "white"],
# ["Jill Michele Melean standup comedy", "white"],
# ["Jim Jefferies standup comedy", "white"],
# ["Jim Tavare standup comedy", "white"],
# ["Jimmy Brogan standup comedy", "white"],
# ["Jimmy Della Valle standup comedy", "white"],
# ["Jimmy Dore standup comedy", "white"],
# ["Jimmy Fallon standup comedy", "white"],
# ["Jimmy Ouyang standup comedy", "white"],
# ["Jimmy Shubert standup comedy", "white"],
# ["Jimmy Tatro standup comedy", "white"],
# ["JJ Whitehead standup comedy", "white"],
# ["Jodi Miller standup comedy", "white"],
# ["Joe Bartnick standup comedy", "white"],
# ["Joe Fernandez standup comedy", "white"],
# ["Joe Kilgallon standup comedy", "white"],
# ["Joe Mande standup comedy", "white"],
# ["Joe Rogan standup comedy", "white"],
# ["Joe Sib standup comedy", "white"],
# ["Joe Starr standup comedy", "white"],
# ["Joel Kim Booster standup comedy", "white"],
# ["Joey Diaz standup comedy", "white"],
# ["Joey Villagomez standup comedy", "white"],
# ["John Austin standup comedy", "white"],
# ["John Campanelli standup comedy", "white"],
# ["John Caponera standup comedy", "white"],
# ["John Clark standup comedy", "white"],
# ["John Crist standup comedy", "white"],
# ["John DiResta standup comedy", "white"],
# ["John Henson standup comedy", "white"],
# ["John Pate standup comedy", "white"],
# ["John Roy standup comedy", "white"],
# ["John Schieszer standup comedy", "white"],
# ["John Tole standup comedy", "white"],
# ["John West standup comedy", "white"],
# ["Johnny Cardinale standup comedy", "white"],
# ["Johnny Pemberton standup comedy", "white"],
# ["Johnny Sanchez standup comedy", "white"],
# ["Johnny Walker standup comedy", "white"],
# ["Jon DeWalt standup comedy", "white"],
# ["Jon Lovitz standup comedy", "white"],
# ["Jon Reep standup comedy", "white"],
# ["Jon Rudnitskys standup comedy", "white"],
# ["Jon Stringer standup comedy", "white"],
# ["Jonah Jurkens standup comedy", "white"],
# ["Jonah Ray standup comedy", "white"],
# ["Jonathan Brown standup comedy", "white"],
# ["Jonathan Kite standup comedy", "white"],
# ["Jonathan Slocumb standup comedy", "white"],
# ["Jonny Loquasto standup comedy", "white"],
# ["Jordan Pease standup comedy", "white"],
# ["Jordan Peele standup comedy", "white"],
# ["Jordan Rubin standup comedy", "white"],
# ["Joseph Ahern standup comedy", "white"],
# ["Josh Adam Meyers standup comedy", "white"],
# ["Josh Alton standup comedy", "white"],
# ["Josh Duvendeck standup comedy", "white"],
# ["Josh Friedman standup comedy", "white"],
# ["Josh Gondelman standup comedy", "white"],
# ["Josh Johnson standup comedy", "white"],
# ["Josh Macuga standup comedy", "white"],
# ["Josh Nasar standup comedy", "white"],
# ["Josh Wade standup comedy", "white"],
# ["Josh Wolf standup comedy", "white"],
# ["Juan Canopii standup comedy", "white"],
# ["Juan Garcia standup comedy", "white"],
# ["Judah Friedlander standup comedy", "white"],
# ["Judy Tenuta standup comedy", "white"],
# ["Julian McCullough standup comedy", "white"],
# ["Julie Goldman standup comedy", "white"],
# ["Junior Stopka standup comedy", "white"],
# ["Justin Foster standup comedy", "white"],
# ["Justin Leon standup comedy", "white"],
# ["Justin Martindale standup comedy", "white"],
# ["Justin Rivera standup comedy", "white"],
# ["Justin Tan standup comedy", "white"],
# ["Justin Vestal standup comedy", "white"],
# ["Justine Marino standup comedy", "white"],
# ["K-von standup comedy", "white"],
# ["Kabir Singh standup comedy", "white"],
# ["Kat Rybarski standup comedy", "white"],
# ["Kate Flannery standup comedy", "white"],
# ["Kathleen Dunbar standup comedy", "white"],
# ["Kathleen Madigan standup comedy", "white"],
# ["Kathleen McGee standup comedy", "white"],
# ["Katy Franco standup comedy", "white"],
# ["Kelly Kane standup comedy", "white"],
# ["Kelly Mantle standup comedy", "white"],
# ["Kellye Howard standup comedy", "white"],
# ["Kelsie Huff standup comedy", "white"],
# ["Ken Garr standup comedy", "white"],
# ["Kenny DeForest standup comedy", "white"],
# ["Kenny Ellis standup comedy", "white"],
# ["Kenny Johnson standup comedy", "white"],
# ["Kenny Kane standup comedy", "white"],
# ["Kento-san standup comedy", "white"],
# ["Kev Orkain standup comedy", "white"],
# ["Kevin Brown standup comedy", "white"],
# ["Kevin Christy standup comedy", "white"],
# ["Kevin Downey Jr standup comedy", "white"],
# ["Kevin Farley standup comedy", "white"],
# ["Kevin Pollak standup comedy", "white"],
# ["Kevin Saul standup comedy", "white"],
# ["Kevin Shea standup comedy", "white"],
# ["Kevin Smith standup comedy", "white"],
# ["Kevin Williams standup comedy", "white"],
# ["Kim Coles standup comedy", "white"],
# ["Kira Soltanovich standup comedy", "white"],
# ["Kirk Fox standup comedy", "white"],
# ["Kris Flanagan standup comedy", "white"],
# ["Kris Rosenberg standup comedy", "white"],
# ["Kristen Toomey standup comedy", "white"],
# ["Kristin Key standup comedy", "white"],
# ["KT Tatara standup comedy", "white"],
# ["Kumail Nanjiani standup comedy", "white"],
# ["Kyle Cease standup comedy", "white"],
# ["Kyle Kinane standup comedy", "white"],
# ["Kyle Scanlan standup comedy", "white"],
# ["Larry Omaha standup comedy", "white"],
# ["Laura Hugg standup comedy", "white"],
# ["Laurie Kilmartin standup comedy", "white"],
# ["Leah Eva standup comedy", "white"],
# ["Lenny Windsor standup comedy", "white"],
# ["Leo Flowers standup comedy", "white"],
# ["Leon Rogers standup comedy", "white"],
# ["Leonard Robinson standup comedy", "white"],
# ["Leslie Jones standup comedy", "white"],
# ["Lester Barrie standup comedy", "white"],
# ["Levi MacDougall standup comedy", "white"],
# ["Lil Rel standup comedy", "white"],
# ["Lindsay Adams standup comedy", "white"],
# ["Lisa Ann Walter standup comedy", "white"],
# ["Liza Treyger standup comedy", "white"],
# ["Logan Guntzelman standup comedy", "white"],
# ["Lou Dinos standup comedy", "white"],
# ["Louie Anderson standup comedy", "white"],
# ["Lowell Sanders standup comedy", "white"],
# ["Lucky Luciano standup comedy", "white"],
# ["Luis Villasenor standup comedy", "white"],
# ["Luke Torres standup comedy", "white"],
# ["Lynda Montgomery standup comedy", "white"],
# ["Mal Hall standup comedy", "white"],
# ["Malik S standup comedy", "white"],
# ["Manny Maldonado standup comedy", "white"],
# ["Marc Maron standup comedy", "white"],
# ["Marc Patrick standup comedy", "white"],
# ["Marcos Lara standup comedy", "white"],
# ["Marcus Steele standup comedy", "white"],
# ["Maria Bamford standup comedy", "white"],
# ["Maria Shehata standup comedy", "white"],
# ["Marilyn Martinez standup comedy", "white"],
# ["Mario Joyner standup comedy", "white"],
# ["Mark Eddie standup comedy", "white"],
# ["Mark Ellis standup comedy", "white"],
# ["Mark Pitta standup comedy", "white"],
# ["Mark Schiff standup comedy", "white"],
# ["Marlon Mitchell standup comedy", "white"],
# ["Maronzio Vance standup comedy", "white"],
# ["Martin Morrow standup comedy", "white"],
# ["Marty DeRosa standup comedy", "white"],
# ["Mary Kennedy standup comedy", "white"],
# ["Mary Lynn Rajskub standup comedy", "white"],
# ["Mary Patterson Broome standup comedy", "white"],
# ["Marz Timms standup comedy", "white"],
# ["Mateen Stewart standup comedy", "white"],
# ["Matt Baetz standup comedy", "white"],
# ["Matt Braunger standup comedy", "white"],
# ["Matt Claybrooks standup comedy", "white"],
# ["Matt Dwyer standup comedy", "white"],
# ["Matt Fulchiron standup comedy", "white"],
# ["Matt Gallagher standup comedy", "white"],
# ["Matt Goldich standup comedy", "white"],
# ["Matt Griffo standup comedy", "white"],
# ["Matt Kissane standup comedy", "white"],
# ["Matt Knost standup comedy", "white"],
# ["Matt Koff standup comedy", "white"],
# ["Matt Lewis standup comedy", "white"],
# ["Matt Marr standup comedy", "white"],
# ["Matt Molchen standup comedy", "white"],
# ["Matt Portman standup comedy", "white"],
# ["Matt Rife standup comedy", "white"],
# ["Matt Riggs standup comedy", "white"],
# ["Matthew Nouriel standup comedy", "white"],
# ["Matthew Taylor standup comedy", "white"],
# ["Matty Doherty standup comedy", "white"],
# ["Matty Goldberg standup comedy", "white"],
# ["Matty Ryan standup comedy", "white"],
# ["Maureen Langan standup comedy", "white"],
# ["Max Alexander standup comedy", "white"],
# ["Max Amini standup comedy", "white"],
# ["Maz Jobrani standup comedy", "white"],
# ["McClinton Neal standup comedy", "white"],
# ["Meechie Hall standup comedy", "white"],
# ["Megan Gailey standup comedy", "white"],
# ["Meghan Murphy standup comedy", "white"],
# ["Mel Novit standup comedy", "white"],
# ["Melissa Shoshahi standup comedy", "white"],
# ["Melissa Villasenor standup comedy", "white"],
# ["Meredeth Zenoff standup comedy", "white"],
# ["MF David Deery standup comedy", "white"],
# ["Micah Bleich standup comedy", "white"],
# ["Michael 'Wheels' Parise standup comedy", "white"],
# ["Michael Colyar standup comedy", "white"],
# ["Michael Cornacchia standup comedy", "white"],
# ["Michael Davis standup comedy", "white"],
# ["Michael Gelbart standup comedy", "white"],
# ["Michael Kosta standup comedy", "white"],
# ["Michael Kvamme standup comedy", "white"],
# ["Michael Magid standup comedy", "white"],
# ["Michael McDonald standup comedy", "white"],
# ["Michael Palascak standup comedy", "white"],
# ["Michael Quu standup comedy", "white"],
# ["Michael Wilhite standup comedy", "white"],
# ["Michele LaCourt standup comedy", "white"],
# ["Michelle Buteau standup comedy", "white"],
# ["Mike Batayeh standup comedy", "white"],
# ["Mike Citera standup comedy", "white"],
# ["Mike Faverman standup comedy", "white"],
# ["Mike Kvamme standup comedy", "white"],
# ["Mike Lebovitz standup comedy", "white"],
# ["Mike Marino standup comedy", "white"],
# ["Mike Muratore standup comedy", "white"],
# ["Mike O'Connel standup comedy", "white"],
# ["Mike O'Malley standup comedy", "white"],
# ["Mike Scott standup comedy", "white"],
# ["Mike Stanley standup comedy", "white"],
# ["Mike Toomey standup comedy", "white"],
# ["Mike Vecchione standup comedy", "white"],
# ["Mike Von standup comedy", "white"],
# ["Mike Wiley standup comedy", "white"],
# ["Mike Young standup comedy", "white"],
# ["Mikko Monroe standup comedy", "white"],
# ["Mindy Rickles standup comedy", "white"],
# ["Mo Amer standup comedy", "white"],
# ["Mo Mandel standup comedy", "white"],
# ["Mo Na standup comedy", "white"],
# ["Momo Rodriguez standup comedy", "white"],
# ["Monique Madrid standup comedy", "white"],
# ["MONROK standup comedy", "white"],
# ["Monty Franklin standup comedy", "white"],
# ["Monty Hoffman standup comedy", "white"],
# ["Mooney Twins standup comedy", "white"],
# ["Morgan Murphy standup comedy", "white"],
# ["Moshe Kasher standup comedy", "white"],
# ["Movses Shakarian standup comedy", "white"],
# ["Mpho Popps standup comedy", "white"],
# ["Mustapha El Atrassi standup comedy", "white"],
# ["Myq Kaplan standup comedy", "white"],
# ["Na'im Lynn standup comedy", "white"],
# ["Narciso Gonzalez standup comedy", "white"],
# ["Natasha Leggero standup comedy", "white"],
# ["Nate Bargatze standup comedy", "white"],
# ["Nate Jackson standup comedy", "white"],
# ["Nate Weatherup standup comedy", "white"],
# ["Neal Brennan standup comedy", "white"],
# ["Neel Kolhatkar standup comedy", "white"],
# ["Nerdvana standup comedy", "white"],
# ["Nick Gaza standup comedy", "white"],
# ["Nick Guerra standup comedy", "white"],
# ["Nick Kroll standup comedy", "white"],
# ["Nick Laughlin standup comedy", "white"],
# ["Nick Lavallee standup comedy", "white"],
# ["Nick Malis standup comedy", "white"],
# ["Nick Petrillo standup comedy", "white"],
# ["Nick Rutherford standup comedy", "white"],
# ["Nick Swardson standup comedy", "white"],
# ["Nick Thune standup comedy", "white"],
# ["Nick Youssef standup comedy", "white"],
# ["Nico Santos standup comedy", "white"],
# ["Nikki Glaser standup comedy", "white"],
# ["Nina Daniels standup comedy", "white"],
# ["Nina Manni standup comedy", "white"],
# ["Noe Gonzalez standup comedy", "white"],
# ["Noelle Lynn standup comedy", "white"],
# ["Norm MacDonald standup comedy", "white"],
# ["Omar Elba standup comedy", "white"],
# ["Omid Singh standup comedy", "white"],
# ["Orlando Jones standup comedy", "white"],
# ["Owen Benjamin standup comedy", "white"],
# ["Owen Smith standup comedy", "white"],
# ["Pablo Rodriguez standup comedy", "white"],
# ["Pardis Parker standup comedy", "white"],
# ["Pat Chase standup comedy", "white"],
# ["Pat Tomasulo standup comedy", "white"],
# ["Patrick DeGuire standup comedy", "white"],
# ["Patrick Garrity standup comedy", "white"],
# ["Patrick Reilly standup comedy", "white"],
# ["Patty Ross standup comedy", "white"],
# ["Paul Farahvar standup comedy", "white"],
# ["Paul Mooney standup comedy", "white"],
# ["Paul Morrissey standup comedy", "white"],
# ["Paul Ogata standup comedy", "white"],
# ["Paul Rodriguez standup comedy", "white"],
# ["Paul Varghese standup comedy", "white"],
# ["Paula Bel standup comedy", "white"],
# ["Pauly Shore standup comedy", "white"],
# ["Pedro Hernandez standup comedy", "white"],
# ["Peet Guercio standup comedy", "white"],
# ["Penny the Prince standup comedy", "white"],
# ["Pete Correale standup comedy", "white"],
# ["Pablo Rodriguez standup comedy", "white"],
# ["Pardis Parker standup comedy", "white"],
# ["Pat Chase standup comedy", "white"],
# ["Pat Tomasulo standup comedy", "white"],
# ["Patrick DeGuire standup comedy", "white"],
# ["Patrick Garrity standup comedy", "white"],
# ["Patrick Reilly standup comedy", "white"],
# ["Patty Ross standup comedy", "white"],
# ["Paul Farahvar standup comedy", "white"],
# ["Paul Mooney standup comedy", "white"],
# ["Paul Morrissey standup comedy", "white"],
# ["Paul Ogata standup comedy", "white"],
# ["Paul Rodriguez standup comedy", "white"],
# ["Paul Varghese standup comedy", "white"],
# ["Paula Bel standup comedy", "white"],
# ["Pauly Shore standup comedy", "white"],
# ["Pedro Hernandez standup comedy", "white"],
# ["Peet Guercio standup comedy", "white"],
# ["Penny the Prince standup comedy", "white"],
# ["Pete Correale standup comedy", "white"],
# ["Pete Davidson standup comedy", "white"],
# ["Pete Holmes standup comedy", "white"],
# ["Peter Berman standup comedy", "white"],
# ["Peter Kim standup comedy", "white"],
# ["Peter the Persian standup comedy", "white"],
# ["Pierce Cassedy standup comedy", "white"],
# ["Piper and Tupper standup comedy", "white"],
# ["PJ McGuire standup comedy", "white"],
# ["Quinn Dahle standup comedy", "white"],
# ["Rachel McDowell standup comedy", "white"],
# ["Rainn Wilson standup comedy", "white"],
# ["Raj Sharma standup comedy", "white"],
# ["Ralph Garman standup comedy", "white"],
# ["Ralph Harris standup comedy", "white"],
# ["Ramon Rivas standup comedy", "white"],
# ["Randy Kagan standup comedy", "white"],
# ["Raq C standup comedy", "white"],
# ["Rashida Lucas standup comedy", "white"],
# ["Rebecca Corry standup comedy", "white"],
# ["Red Grant standup comedy", "white"],
# ["Reena Calm standup comedy", "white"],
# ["Reggie Jr. standup comedy", "white"],
# ["Rene Garcia standup comedy", "white"],
# ["Rex Navarrete standup comedy", "white"],
# ["Reyna Amaya standup comedy", "white"],
# ["Reza Farahan standup comedy", "white"],
# ["Ricardo Martinez standup comedy", "white"],
# ["Rich Hall standup comedy", "white"],
# ["Rich Vos standup comedy", "white"],
# ["Rich Wentz standup comedy", "white"],
# ["Richard Bain standup comedy", "white"],
# ["Richard Chassler standup comedy", "white"],
# ["Richard Traub standup comedy", "white"],
# ["Richard Villa standup comedy", "white"],
# ["Rick Bryan standup comedy", "white"],
# ["Rick Gutierrez standup comedy", "white"],
# ["Rick Ingraham standup comedy", "white"],
# ["Rick Overton standup comedy", "white"],
# ["Rick Ramos standup comedy", "white"],
# ["Ricky Carmona standup comedy", "white"],
# ["Ricky Gonzalez standup comedy", "white"],
# ["Rico Parrish standup comedy", "white"],
# ["Ritch Shydner standup comedy", "white"],
# ["Ro DelleGrazie standup comedy", "white"],
# ["Rob 'Lil Rob' Robledo standup comedy", "white"],
# ["Rob DaRocha standup comedy", "white"],
# ["Rob Delaney standup comedy", "white"],
# ["Rob Gleeson standup comedy", "white"],
# ["Rob Lindo standup comedy", "white"],
# ["Rob O'Reilly standup comedy", "white"],
# ["Rob Schneider standup comedy", "white"],
# ["Rob Sherwood standup comedy", "white"],
# ["Robbie Pickard standup comedy", "white"],
# ["Robby Slowik standup comedy", "white"],
# ["Robert Kelly standup comedy", "white"],
# ["Robert Powell standup comedy", "white"],
# ["Robert Robledo standup comedy", "white"],
# ["Robert Rothstein standup comedy", "white"],
# ["Robert Zapata standup comedy", "white"],
# ["Robin Higgins standup comedy", "white"],
# ["Rodney Lumpkins standup comedy", "white"],
# ["Rodrigo Torres standup comedy", "white"],
# ["Ron Babcock standup comedy", "white"],
# ["Ron Funches standup comedy", "white"],
# ["Ron G standup comedy", "white"],
# ["Ron Josol standup comedy", "white"],
# ["Ron Lynch standup comedy", "white"],
# ["Ron Pearson standup comedy", "white"],
# ["Ron Swallow standup comedy", "white"],
# ["Ron White standup comedy", "white"],
# ["Ronn Vigh standup comedy", "white"],
# ["Ronnie Khalil standup comedy", "white"],
# ["Ronnie Ray standup comedy", "white"],
# ["Rory Albanese standup comedy", "white"],
# ["Rory Scovel standup comedy", "white"],
# ["Roseanne Barr standup comedy", "white"],
# ["Roy Wood Jr. standup comedy", "white"],
# ["Royale Watkins standup comedy", "white"],
# ["Roz Browne standup comedy", "white"],
# ["Ruben Paul standup comedy", "white"],
# ["Russ Williamson standup comedy", "white"],
# ["Russell Hicks standup comedy", "white"],
# ["Rusty Dooley standup comedy", "white"],
# ["Ryan Hynek standup comedy", "white"],
# ["Ryan O'Flanagan standup comedy", "white"],
# ["Ryan Salzwedel standup comedy", "white"],
# ["Ryan Sickler standup comedy", "white"],
# ["Ryan Singer standup comedy", "white"],
# ["Ryan Stout standup comedy", "white"],
# ["Ryan Walker standup comedy", "white"],
# ["CBAZZ standup comedy", "white"],
# ["Sadiki Fuller standup comedy", "white"],
# ["Sam Boyer standup comedy", "white"],
# ["Sam Kwasman standup comedy", "white"],
# ["Sam Tripoli standup comedy", "white"],
# ["Sammy Obeid standup comedy", "white"],
# ["Sammy Shore standup comedy", "white"],
# ["Samuel Comroe standup comedy", "white"],
# ["Sandra Pena standup comedy", "white"],
# ["Sandra Valls standup comedy", "white"],
# ["Sandro Iocolano standup comedy", "white"],
# ["Sandy Danto standup comedy", "white"],
# ["Sarah Taylor standup comedy", "white"],
# ["Sarah Tiana standup comedy", "white"],
# ["Saurin Choksi standup comedy", "white"],
# ["Sax Carr standup comedy", "white"],
# ["Schmitty B standup comedy", "white"],
# ["Scott Blacks standup comedy", "white"],
# ["Scott Duff standup comedy", "white"],
# ["Scott King standup comedy", "white"],
# ["Scott Krinsky standup comedy", "white"],
# ["Scott LaRose standup comedy", "white"],
# ["Scout Durwood standup comedy", "white"],
# ["Sean Flannery standup comedy", "white"],
# ["Sean O'Connor standup comedy", "white"],
# ["Sean Parker standup comedy", "white"],
# ["Sean Patton standup comedy", "white"],
# ["Sean Tweedley standup comedy", "white"],
# ["Sebastian Cetina standup comedy", "white"],
# ["Sebastian Maniscalco standup comedy", "white"],
# ["Shane Copeland standup comedy", "white"],
# ["ShangShang standup comedy", "white"],
# ["Sharon Houston standup comedy", "white"],
# ["Shaun Latham standup comedy", "white"],
# ["Shawn Pelofsky standup comedy", "white"],
# ["Shayma Tash standup comedy", "white"],
# ["Shelagh Ratner standup comedy", "white"],
# ["Shelby standup comedy", "white"],
# ["Sherman Edwards standup comedy", "white"],
# ["Sherwin Arae standup comedy", "white"],
# ["Shuli Egar standup comedy", "white"],
# ["Sister Myotis standup comedy", "white"],
# ["Skyler Stone standup comedy", "white"],
# ["Soli Santos standup comedy", "white"],
# ["Spoiled Seed standup comedy", "white"],
# ["Stan Morrow standup comedy", "white"],
# ["Stephanie Blum standup comedy", "white"],
# ["Stephanie Hasz standup comedy", "white"],
# ["Stephen C. James standup comedy", "white"],
# ["Stephen Glickman standup comedy", "white"],
# ["Stephen Thomas standup comedy", "white"],
# ["Steve 'Mudflap' McGrew standup comedy", "white"],
# ["Steve Flye standup comedy", "white"],
# ["Steve Hofstetter standup comedy", "white"],
# ["Steve Mittleman standup comedy", "white"],
# ["Steve Rannazzisi standup comedy", "white"],
# ["Steve Shaffer standup comedy", "white"],
# ["Steve Simeone standup comedy", "white"],
# ["Steve Trevino standup comedy", "white"],
# ["Steve White standup comedy", "white"],
# ["Steve Wilson standup comedy", "white"],
# ["Steve-O standup comedy", "white"],
# ["Steven Pearl standup comedy", "white"],
# ["Steven Wright standup comedy", "white"],
# ["Streeter Seidell standup comedy", "white"],
# ["Stroy Moyd standup comedy", "white"],
# ["Sue Costello standup comedy", "white"],
# ["Suli McCullough standup comedy", "white"],
# ["Sunda Croonquist standup comedy", "white"],
# ["Sydney Adeniyi standup comedy", "white"],
# ["Sydney Castillo standup comedy", "white"],
# ["Rell Battle standup comedy", "white"],
# ["Tamer Kattan standup comedy", "white"],
# ["Taneshia Rice standup comedy", "white"],
# ["Tanmay Bhat standup comedy", "white"],
# ["Tanya Lee Davis standup comedy", "white"],
# ["Tara Egnatios standup comedy", "white"],
# ["Tara Terry standup comedy", "white"],
# ["Taryn Southern standup comedy", "white"],
# ["Taylor Williamson standup comedy", "white"],
# ["Taylor Wolfe standup comedy", "white"],
# ["Teddy Margas standup comedy", "white"],
# ["Thai Rivera standup comedy", "white"],
# ["The Greg Wilson standup comedy", "white"],
# ["Theo Von standup comedy", "white"],
# ["Tiffany Haddish standup comedy", "white"],
# ["Tig Notaro standup comedy", "white"],
# ["Tim Durham standup comedy", "white"],
# ["Tim Gaither standup comedy", "white"],
# ["Tim Jones standup comedy", "white"],
# ["Tim Lim standup comedy", "white"],
# ["Tim Meadows standup comedy", "white"],
# ["Tim Powers standup comedy", "white"],
# ["Timm Metivier standup comedy", "white"],
# ["Timmy Brochu standup comedy", "white"],
# ["TJ Miller standup comedy", "white"],
# ["Tobe Hixx standup comedy", "white"],
# ["Todd Glass standup comedy", "white"],
# ["Todd Masterson standup comedy", "white"],
# ["Todd Rexx standup comedy", "white"],
# ["Tom Clark standup comedy", "white"],
# ["Tom Dreesen standup comedy", "white"],
# ["Tom Franck standup comedy", "white"],
# ["Tom Green standup comedy", "white"],
# ["Tom Papa standup comedy", "white"],
# ["Tom Rhode standup comedy", "white"],
# ["Tommy Davidson standup comedy", "white"],
# ["Tommy Gimler standup comedy", "white"],
# ["Tommy Johnagin standup comedy", "white"],
# ["Tommy Mac standup comedy", "white"],
# ["Tommy Savitt standup comedy", "white"],
# ["Tommy Waas standup comedy", "white"],
# ["Tone Bell standup comedy", "white"],
# ["Tony Baker standup comedy", "white"],
# ["Tony Rock standup comedy", "white"],
# ["Tony Sculfield standup comedy", "white"],
# ["Tristan Triptow standup comedy", "white"],
# ["Trizah Morris standup comedy", "white"],
# ["Tyler Austin standup comedy", "white"],
# ["Tyler Boeh standup comedy", "white"],
# ["Tyler Greene standup comedy", "white"],
# ["Tyler Spindel standup comedy", "white"],
# ["Tyler Warner standup comedy", "white"],
# ["Vanessa Graddick standup comedy", "white"],
# ["Vargus Mason standup comedy", "white"],
# ["Vic Henley standup comedy", "white"],
# ["Vicki Barbolak standup comedy", "white"],
# ["Vicki Wagner standup comedy", "white"],
# ["Vince Acevedo standup comedy", "white"],
# ["Vince Carone standup comedy", "white"],
# ["Vincent Oshana standup comedy", "white"],
# ["Walter Hong standup comedy", "white"],
# ["Wayne Federman standup comedy", "white"],
# ["Wendy Liebman standup comedy", "white"],
# ["Whitney Cummings standup comedy", "white"],
# ["Whitney Rice standup comedy", "white"],
# ["Wil Anderson standup comedy", "white"],
# ["Wild Willy Parsons standup comedy", "white"],
# ["Will Lee-Williams standup comedy", "white"],
# ["Will Moles standup comedy", "white"],
# ["Willie Barcena standup comedy", "white"],
# ["Willie Hunter standup comedy", "white"],
# ["Willis Turner standup comedy", "white"],
# ["Xavier Lamont standup comedy", "white"],
# ["Yassir Lester standup comedy", "white"],
# ["Yeshmin Blechin standup comedy", "white"],
# ["Yoursite Thomas standup comedy", "white"],
# ["Zachary Katz standup comedy", "white"],
# ["Zachary Pincus-Roth standup comedy", "white"],
# ["Zan Aufderheide standup comedy", "white"],
# ["Zara Mizrahi standup comedy", "white"],
["Zhivago Blea standup comedy"]
]

counter = 1

Comedian.create(name: "_no_name")
User.create(email: "admin@waste5.com", password: "admin_only", name: "Aditya Mahesh", is_admin: true)

comedians.each do |comedian|
  p "#{counter} / #{comedians.length} | #{comedian}"
  counter += 1
  opts = Trollop::options do
    opt :q, 'Search term', :type => String, :default => comedian[0]
    opt :maxResults, 'Max results', :type => :int, :default => 10
  end
  # Call the search.list method to retrieve results matching the specified
  # query term.
  opts[:part] = 'id,snippet'
  search_response = client.execute!(
    :api_method => youtube.search.list,
    :parameters => opts
  )
  # Create results
  search_response.data.items.each do |search_result|
    if search_result.id.kind == 'youtube#video'
      comedian_name = comedian[0].split(" standup")[0]
      Comedian.find_or_create_by_name(comedian_name)
      current_comedian = Comedian.find_by_name(comedian_name)
      category = comedian[1]
      video = yt_client.video_by(search_result.id.videoId)

      # video.rating.average ? rating = video.rating.average : rating = 0

      # if video.rating.average
      #   if video.noembed == false && video.view_count > 50000 && video.rating.average > 3
      #     Post.create(youtube_id: id, title: title, description: description, date: uploaded_at, view_count: view_count, duration: duration, comedian_name: comedian_name, rating: rating)
      #   end
      # else
        if video.noembed == false && video.view_count > 50000 && video.duration > 60
          id = video.unique_id
          title = video.title
          video.description ? description = video.description : description = ""
          video.uploaded_at ? uploaded_at = video.uploaded_at : uploaded_at = "2000-01-01 01:01:01.000000"
          video.view_count ? view_count = video.view_count : view_count = 0
          video.duration ? duration = video.duration : duration = 0
          Post.create(youtube_id: id, title: title, description: description, date: uploaded_at, view_count: view_count, duration: duration, comedian_id: current_comedian.id, category: category)
        end
      # end
    end
  end
end


