#encoding: utf-8

#!/usr/bin/ruby

require 'rubygems'
require 'google/api_client'
require 'trollop'


# Set DEVELOPER_KEY to the "API key" value from the "Access" tab of the
# Google Developers Console <https://cloud.google.com/console>
# Please ensure that you have enabled the YouTube Data API for your project.
DEVELOPER_KEY = "AIzaSyCE0MVxKIJWDbbcfFBDwqD2PW7Igpo8zwY"
YOUTUBE_API_SERVICE_NAME = "youtube"
YOUTUBE_API_VERSION = "v3"
client = Google::APIClient.new(:key => DEVELOPER_KEY,
                               :authorization => nil)
youtube = client.discovered_api(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION)

comedians =  ["Orny Adams standup comedy",
"Ahmed Ahmed standup comedy",
"Max Alexander standup comedy",
"Dan Allen standup comedy",
"Fred Allen standup comedy",
"Steve Allen standup comedy",
"Tim Allen standup comedy",
"Woody Allen standup comedy",
"Rabbi Bob Alper standup comedy",
"Jeff Altman standup comedy",
"Louie Anderson standup comedy",
"Eric André standup comedy",
"Aziz Ansari standup comedy",
"Craig Anton standup comedy",
"Dave Attell standup comedy",
"Rick Aviles standup comedy",
"Ben Bailey standup comedy",
"Maria Bamford standup comedy",
"Arj Barker standup comedy",
"Roseanne Barr standup comedy",
"Chuck Barris standup comedy",
"Todd Barry standup comedy",
"Greg Behrendt standup comedy",
"Richard Belzer standup comedy",
"Jack Benny standup comedy",
"Doug Benson standup comedy",
"Milton Berle standup comedy",
"Shelley Berman standup comedy",
"Sandra Bernhard standup comedy",
"Michelle Biloon standup comedy",
"Mike Birbiglia standup comedy",
"Joey Bishop standup comedy",
"Lewis Black standup comedy",
"Michael Ian Black standup comedy",
"Chris Bliss standup comedy",
"Josh Blue standup comedy",
"Elayne Boosler standup comedy",
"Joey Bragg standup comedy",
"Matt Braunger standup comedy",
"Shaun Eli Breidbart standup comedy",
"Kevin Brennan standup comedy",
"David Brenner standup comedy",
"Jim Breuer standup comedy",
"Bruce Bruce standup comedy",
"Lenny Bruce standup comedy",
"Andy Bumatai standup comedy",
"Bo Burnham standup comedy",
"George Burns standup comedy",
"Bill Burr standup comedy",
"Hannibal Buress standup comedy",
"Brett Butler standup comedy",
"Red Buttons standup comedy",
"John Byner standup comedy",
"Louis CK standup comedy",
"Frank Caliendo standup comedy",
"Godfrey Cambridge standup comedy",
"Mario Cantone standup comedy",
"John Caparulo standup comedy",
"John Caponera standup comedy",
"Scott Capurro standup comedy",
"Steve Carell standup comedy",
"George Carlin standup comedy",
"Drew Carey standup comedy",
"Adam Carolla standup comedy",
"Jim Carrey standup comedy",
"Rodney Carrington standup comedy",
"Carrot Top  standup comedy",
"Darren Carter standup comedy",
"Jack Carter standup comedy",
"Dana Carvey standup comedy",
"Kyle Cease standup comedy",
"Cedric the Entertainer standup comedy",
"Dave Chappelle standup comedy",
"Henry Cho standup comedy",
"Margaret Cho standup comedy",
"Tommy Chong standup comedy",
"Blake Clark standup comedy",
"Andrew Dice Clay standup comedy",
"Kate Clinton standup comedy",
"Bobby Collins standup comedy",
"Kaitlin Colombo standup comedy",
"Ray Combs standup comedy",
"Dane Cook standup comedy",
"Brian Copeland standup comedy",
"Irwin Corey standup comedy",
"Bill Cosby standup comedy",
"Dave Coulier standup comedy",
"David Cross standup comedy",
"Billy Crystal standup comedy",
"Godfrey Danchimah standup comedy",
"Rodney Dangerfield standup comedy",
"Ron Darian standup comedy",
"Jim David standup comedy",
"Larry David standup comedy",
"Dov Davidoff standup comedy",
"DeRay Davis standup comedy",
"Frank DeCaro standup comedy",
"Ellen DeGeneres standup comedy",
"Lea DeLaria standup comedy",
"Frank Delima standup comedy",
"Nick DiPaolo standup comedy",
"Dustin Diamond standup comedy",
"Andy Dick standup comedy",
"Phyllis Diller standup comedy",
"Jeff Dunham standup comedy",
"Jeff Dye standup comedy",
"Earthquake standup comedy",
"Sally Edwards standup comedy",
"Bill Engvall standup comedy",
"Mike Epps standup comedy",
"Susie Essman standup comedy",
"Jade Esteban Estrada standup comedy",
"Mitch Fatel standup comedy",
"Wayne Federman standup comedy",
"Craig Ferguson standup comedy",
"Adam Ferrara standup comedy",
"Totie Fields standup comedy",
"Christian Finnegan standup comedy",
"Kevin Fitzgerald standup comedy",
"Greg Fitzsimmons standup comedy",
"Maile Flanagan standup comedy",
"Charles Fleischer standup comedy",
"Jim Florentine standup comedy",
"John Fox standup comedy",
"Kirk Fox standup comedy",
"Jeff Foxworthy standup comedy",
"Jamie Foxx standup comedy",
"Redd Foxx standup comedy",
"Pablo Francisco standup comedy",
"Jim Gaffigan standup comedy",
"Zach Galifianakis standup comedy",
"Gallagher standup comedy",
"Billy Gardell standup comedy",
"Jeff Garlin standup comedy",
"Janeane Garofalo standup comedy",
"Brad Garrett standup comedy",
"Greg Giraldo standup comedy",
"Adele Givens standup comedy",
"Todd Glass standup comedy",
"Donald Glover standup comedy",
"Judy Gold standup comedy",
"Whoopi Goldberg standup comedy",
"Bobcat Goldthwait standup comedy",
"Bob Golub standup comedy",
"Marga Gomez standup comedy",
"Gilbert Gottfried standup comedy",
"Dana Gould standup comedy",
"Shecky Greene standup comedy",
"Dick Gregory standup comedy",
"James Gregory standup comedy",
"David Alan Grier standup comedy",
"Eddie Griffin standup comedy",
"Kathy Griffin standup comedy",
"Andy Griffith standup comedy",
"Gary Gulman standup comedy",
"Buddy Hackett standup comedy",
"Brian Haley standup comedy",
"Arsenio Hall standup comedy",
"Nathan Hall standup comedy",
"Rich Hall standup comedy",
"Neil Hamburger standup comedy",
"Ashley Hamilton standup comedy",
"Darrell Hammond standup comedy",
"Stanley Myron Handelman standup comedy",
"Chelsea Handler standup comedy",
"Chris Hardwick standup comedy",
"Johnny Hardwick standup comedy",
"Ralph Harris standup comedy",
"Kevin Hart standup comedy",
"Steve Harvey standup comedy",
"Drew Hastings standup comedy",
"Allan Havey standup comedy",
"David C. Hayes standup comedy",
"Mitch Hedberg standup comedy",
"Bill Hicks standup comedy",
"René Hicks standup comedy",
"Steve Hofstetter standup comedy",
"Pete Holmes standup comedy",
"Bob Hope standup comedy",
"DL Hughley standup comedy",
"Reginald D Hunter standup comedy",
"Gabriel Iglesias standup comedy",
"Dom Irrera standup comedy",
"Clinton Jackson standup comedy",
"Kevin James standup comedy",
"Richard Jeni standup comedy",
"Anthony Jeselnik standup comedy",
"Maz Jobrani standup comedy",
"Jake Johannsen standup comedy",
"Leslie Jordan standup comedy",
"Aron Kader standup comedy",
"Cory Kahaney standup comedy",
"Moshe Kasher standup comedy",
"Andy Kaufman standup comedy",
"Jamie Kennedy standup comedy",
"Jimmy Kimmel standup comedy",
"Kyle Kinane standup comedy",
"Andy Kindler standup comedy",
"Alan King standup comedy",
"Sam Kinison standup comedy",
"Jen Kirkman standup comedy",
"Robert Klein standup comedy",
"Jeff Klinger standup comedy",
"Don Knotts standup comedy",
"Rebekah Kochan standup comedy",
"Lynne Koplitz standup comedy",
"Jo Koy standup comedy",
"Lisa Lampanelli standup comedy",
"Lisa Landry standup comedy",
"Artie Lange standup comedy",
"Larry the Cable Guy standup comedy",
"Martin Lawrence standup comedy",
"Denis Leary standup comedy",
"Natasha Leggero standup comedy",
"John Leguizamo standup comedy",
"Tom Lehrer standup comedy",
"Carol Leifer standup comedy",
"Jay Leno standup comedy",
"David Letterman standup comedy",
"Emily Levine standup comedy",
"Wendy Liebman standup comedy",
"Rob Little standup comedy",
"Jay London standup comedy",
"George Lopez standup comedy",
"Jason Love standup comedy",
"Loni Love standup comedy",
"Jon Lovitz standup comedy",
"Stephen Lynch standup comedy",
"Paul Lynde standup comedy",
"Moms Mabley standup comedy",
"Bernie Mac standup comedy",
"Norm Macdonald standup comedy",
"Kathleen Madigan standup comedy",
"Al Madrigal standup comedy",
"Bill Maher standup comedy",
"Keith Malley standup comedy",
"Cheech Marin standup comedy",
"Bob Marley standup comedy",
"Marc Maron standup comedy",
"Steve Martin standup comedy",
"Demetri Martin standup comedy",
"Marilyn Martinez standup comedy",
"Jackie Martling standup comedy",
"Jackie Mason standup comedy",
"Ralphie May standup comedy",
"Jonny McGovern standup comedy",
"Joel McHale standup comedy",
"Kevin Meaney standup comedy",
"Anne Meara standup comedy",
"Carlos Mencia standup comedy",
"Russ Meneve standup comedy",
"Seth Meyers standup comedy",
"Dennis Miller standup comedy",
"George Miller standup comedy",
"Larry Miller standup comedy",
"Eugene Mirman standup comedy",
"MoNique standup comedy",
"Tracy Morgan standup comedy",
"Paul Mooney standup comedy",
"Rudy Ray Moore standup comedy",
"Kevin Moyers standup comedy",
"John Mulaney standup comedy",
"Charlie Murphy standup comedy",
"Eddie Murphy standup comedy",
"Noel Murphy standup comedy",
"Kumail Nanjiani standup comedy",
"Bob Newhart standup comedy",
"Adam Newman standup comedy",
"Lance Norris standup comedy",
"Jim Norton standup comedy",
"Tig Notaro standup comedy",
"Dean Obeidallah standup comedy",
"Conan O Brien standup comedy",
"Rosie O Donnell standup comedy",
"Paul Ogata standup comedy",
"Patrice O Neal standup comedy",
"Patton Oswalt standup comedy",
"Jimmy Pardo standup comedy",
"Minnie Pearl standup comedy",
"Emo Philips standup comedy",
"John Pinette standup comedy",
"Aubrey Plaza standup comedy",
"Brian Posehn standup comedy",
"Paula Poundstone standup comedy",
"Marc Price standup comedy",
"Freddie Prinze standup comedy",
"Greg Proops standup comedy",
"Paul Provenza standup comedy",
"Richard Pryor standup comedy",
"Colin Quinn standup comedy",
"David Race standup comedy",
"Brian Regan standup comedy",
"Paul Reiser standup comedy",
"Michael Richards standup comedy",
"Don Rickles standup comedy",
"Joan Rivers standup comedy",
"Craig Robinson standup comedy",
"Chris Rock standup comedy",
"Paul Rodriguez standup comedy",
"Joe Rogan standup comedy",
"Seth Rogen standup comedy",
"Ray Romano standup comedy",
"Jeffrey Ross standup comedy",
"Rita Rudner standup comedy",
"Chris Rush standup comedy",
"Nipsey Russell standup comedy",
"Bob Saget standup comedy",
"Tim Sample standup comedy",
"Adam Sandler standup comedy",
"Lewis Schaffer standup comedy",
"Mark Schiff standup comedy",
"Robert Schimmel standup comedy",
"Amy Schumer standup comedy",
"Jerry Seinfeld standup comedy",
"Garry Shandling standup comedy",
"Rick Shapiro standup comedy",
"Ron Shock standup comedy",
"Craig Shoemaker standup comedy",
"Ritch Shydner standup comedy",
"Sarah Silverman standup comedy",
"Red Skelton standup comedy",
"Brad Slaight standup comedy",
"Bobby Slayton standup comedy",
"Yakov Smirnoff standup comedy",
"Margaret Smith standup comedy",
"Sommore standup comedy",
"David Spade standup comedy",
"Doug Stanhope standup comedy",
"Brody Stevens standup comedy",
"Jon Stewart standup comedy",
"Jerry Stiller standup comedy",
"Brad Stine standup comedy",
"Fred Stoller standup comedy",
"Ryan Stout standup comedy",
"Nick Swardson standup comedy",
"Wanda Sykes standup comedy",
"Tim Tayag standup comedy",
"Judy Tenuta standup comedy",
"Danny Thomas standup comedy",
"Jimmy Tingle standup comedy",
"Christopher Titus standup comedy",
"Lily Tomlin standup comedy",
"Paul F. Tompkins standup comedy",
"Daniel Tosh standup comedy",
"Rosie Tran standup comedy",
"Fred Travalena standup comedy",
"Greg Travis standup comedy",
"Chris Tucker standup comedy",
"Rich Vos standup comedy",
"Jimmie Walker standup comedy",
"Greg Warren standup comedy",
"Damon Wayans standup comedy",
"Keenen Ivory Wayans standup comedy",
"Shawn Wayans standup comedy",
"Suzanne Westenhoefer standup comedy",
"Ron White standup comedy",
"Katt Williams standup comedy",
"Robin Williams standup comedy",
"Flip Wilson standup comedy",
"Michael Winslow standup comedy",
"Jonathan Winters standup comedy",
"Mark Wirtz standup comedy",
"Harris Wittels standup comedy",
"Dennis Wolfberg standup comedy",
"Steven Wright standu comedy"]

comedians.each do |comedian|
  opts = Trollop::options do
    opt :q, 'Search term', :type => String, :default => comedian
    opt :maxResults, 'Max results', :type => :int, :default => 10
  end
  # Call the search.list method to retrieve results matching the specified
  # query term.
  opts[:part] = 'id,snippet'
  search_response = client.execute!(
    :api_method => youtube.search.list,
    :parameters => opts
  )
  # Create results
  search_response.data.items.each do |search_result|
    if search_result.id.kind == 'youtube#video'
      Post.create(youtube_id: search_result.id.videoId, title: search_result.snippet.title, description: search_result.snippet.description, date: search_result.snippet.publishedAt)
    end
  end
end


